# ============================================================
# IAM Users, Groups, and Custom Policies
# ============================================================
# 22 IAM Users (manually created), 6 Groups, key custom policies
# These are console/human users, NOT service roles (those are in iam.tf)
# ============================================================

# ---------- IAM Users ----------
locals {
  iam_users = toset([
    "ahmad.almudhi",
    "ahmad.dd",
    "Fareed.AbdulHameed",
    "Gitlab-User",
    "lokesh.ramesh@muvicinemas.com",
    "m.elsherif",
    "m.hamdy",
    "m.wehbe",
    "manar.almalki",
    "mohammed.shaker",
    "muhammad.faisal@muvicinemas.com",
    "parameter-store-readonly",
    "poc@muvicinemas.com",
    "rehan.tariq@muvicinemas.com",
    "s3",
    "Saad.Taqieddin",
    "shahriyar.agha@muvicinemas.com",
    "subs.account@muvicinemas.com",
    "syed.faheem@muvicinemas.com",
    "syed.mansoor@muvicinemas.com",
    "Usman.Malik",
    "wilfredo.perez",
    "zeeshan.mehboob@muvicinemas.com",
  ])
}

resource "aws_iam_user" "users" {
  for_each = local.iam_users
  name     = each.key

  tags = { Name = each.key }

  lifecycle {
    ignore_changes = [tags, path, permissions_boundary, force_destroy]
  }
}

# ---------- IAM Groups ----------
resource "aws_iam_group" "admins" {
  name = "Admins"
}

resource "aws_iam_group" "gitlab" {
  name = "Gitlab"
}

resource "aws_iam_group" "readonly" {
  name = "ReadOnly"
}

resource "aws_iam_group" "s3_admins" {
  name = "S3-Admins"
}

resource "aws_iam_group" "subs_account" {
  name = "subs.account"
}

resource "aws_iam_group" "zeroand1" {
  name = "ZeroAnd1"
}

# ---------- Key Custom Policies ----------
# Note: ~110+ policies exist, many auto-generated by CodePipeline/CodeBuild/Lambda/EventBridge.
# Only recording the key custom/manual policies here.
# Service-generated policies (AWSLambdaBasicExecutionRole-*, CodeBuildBasePolicy-*, etc.)
# are implicitly managed via the IAM roles in iam.tf.

resource "aws_iam_policy" "force_mfa" {
  name = "Force-MFA"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowViewAccountInfo"
        Effect = "Allow"
        Action = [
          "iam:GetAccountPasswordPolicy",
          "iam:ListVirtualMFADevices"
        ]
        Resource = "*"
      },
      {
        Sid    = "AllowManageOwnVirtualMFADevice"
        Effect = "Allow"
        Action = [
          "iam:CreateVirtualMFADevice",
          "iam:DeleteVirtualMFADevice"
        ]
        Resource = "arn:aws:iam::${var.account_id}:mfa/$${aws:username}"
      },
      {
        Sid    = "AllowManageOwnUserMFA"
        Effect = "Allow"
        Action = [
          "iam:DeactivateMFADevice",
          "iam:EnableMFADevice",
          "iam:GetUser",
          "iam:ListMFADevices",
          "iam:ResyncMFADevice"
        ]
        Resource = "arn:aws:iam::${var.account_id}:user/$${aws:username}"
      },
      {
        Sid    = "DenyAllExceptListedIfNoMFA"
        Effect = "Deny"
        NotAction = [
          "iam:CreateVirtualMFADevice",
          "iam:EnableMFADevice",
          "iam:GetUser",
          "iam:ListMFADevices",
          "iam:ListVirtualMFADevices",
          "iam:ResyncMFADevice",
          "sts:GetSessionToken"
        ]
        Resource = "*"
        Condition = {
          BoolIfExists = { "aws:MultiFactorAuthPresent" = "false" }
        }
      }
    ]
  })

  lifecycle {
    ignore_changes = [policy]
  }
}

resource "aws_iam_policy" "mfa_access" {
  name = "MFA_Access"
  policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{ Effect = "Allow", Action = "iam:*MFA*", Resource = "*" }]
  })

  lifecycle {
    ignore_changes = [policy]
  }
}

resource "aws_iam_policy" "parameter_store_readonly" {
  name = "parameter-store-ReadOnly"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "ssm:DescribeParameters",
        "ssm:GetParameter",
        "ssm:GetParameters",
        "ssm:GetParametersByPath"
      ]
      Resource = "*"
    }]
  })

  lifecycle {
    ignore_changes = [policy]
  }
}

resource "aws_iam_policy" "athena_access" {
  name = "AthenaAccess"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "athena:*",
          "glue:*"
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = ["s3:*"]
        Resource = [
          "arn:aws:s3:::muvi-athena",
          "arn:aws:s3:::muvi-athena/*",
          "arn:aws:s3:::aws-athena-query-results-eu-central-1-${var.account_id}",
          "arn:aws:s3:::aws-athena-query-results-eu-central-1-${var.account_id}/*"
        ]
      }
    ]
  })

  lifecycle {
    ignore_changes = [policy]
  }
}

# ---------- S3 Replication IAM Roles ----------
# Used by S3 cross-region replication for media and CMS DR

resource "aws_iam_role" "s3crr_media" {
  name = "s3crr_role_for_muvi-media-prod"
  path = "/service-role/"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "s3.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  lifecycle {
    ignore_changes = [assume_role_policy]
  }
}

resource "aws_iam_role_policy" "s3crr_media" {
  name = "s3crr_policy_for_muvi-media-prod"
  role = aws_iam_role.s3crr_media.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetReplicationConfiguration",
          "s3:ListBucket"
        ]
        Resource = "arn:aws:s3:::muvi-media-prod"
      },
      {
        Effect   = "Allow"
        Action   = ["s3:GetObjectVersionForReplication", "s3:GetObjectVersionAcl", "s3:GetObjectVersionTagging"]
        Resource = "arn:aws:s3:::muvi-media-prod/*"
      },
      {
        Effect   = "Allow"
        Action   = ["s3:ReplicateObject", "s3:ReplicateDelete", "s3:ReplicateTags"]
        Resource = "arn:aws:s3:::muvi-media-prod-dr/*"
      }
    ]
  })

  lifecycle {
    ignore_changes = [policy]
  }
}

resource "aws_iam_role" "s3crr_cms" {
  name = "s3crr_role_for_muvi-cms-prod_1"
  path = "/service-role/"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "s3.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  lifecycle {
    ignore_changes = [assume_role_policy]
  }
}

resource "aws_iam_role_policy" "s3crr_cms" {
  name = "s3crr_policy_for_muvi-cms-prod"
  role = aws_iam_role.s3crr_cms.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetReplicationConfiguration",
          "s3:ListBucket"
        ]
        Resource = "arn:aws:s3:::muvi-cms-prod"
      },
      {
        Effect   = "Allow"
        Action   = ["s3:GetObjectVersionForReplication", "s3:GetObjectVersionAcl", "s3:GetObjectVersionTagging"]
        Resource = "arn:aws:s3:::muvi-cms-prod/*"
      },
      {
        Effect   = "Allow"
        Action   = ["s3:ReplicateObject", "s3:ReplicateDelete", "s3:ReplicateTags"]
        Resource = "arn:aws:s3:::muvi-cms-prod-dr/*"
      }
    ]
  })

  lifecycle {
    ignore_changes = [policy]
  }
}
