export const BAD_REQUEST = 'BAD_REQUEST';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const UNHANDELED = 'UNHANDELED';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
